# Base linux image. Docker recommends Debian, but we'll
# use CentOS to be consistent with what already installed 

from centos:latest

# I never asked for this
MAINTAINER Roman Kuzmichev <daerdemandt@gmail.com>
LABEL Description="This image is used to base on it other linux images"
 
